---

#constellation parameters 
LEOConstellation: 'Walker Star'
NumberLEOSatellites: 360
OrbitalPlanes: 20
Inclination: 80 
phasingParameter: 5
orbitAltitudeLEO: 1000000

#base station and environment parameters 
earthRadius: 6371000
BaseStationLocations: 
  - [82.5, -62.3] 
  - [70.4, -31.1]
BaseStationViewAngle: 10
SunExclusionAngle: 40
SunLocation: [149.6e+6, 0, 0]

#topology and routing polocy / satellite info
initialTopology: 'IPO'
routingPolicy: null
topologyPolicy: null
packetProcessRate: 1

#simulation runtime parameters 
numPeople: 10
numPacketsPerPerson: 10
packetSendTimeFrame: .1
personDistribution: 'PseudoUniform'

queingDelaysEnabled: 'True'
weatherEnabled: 'False'
environmentUpdateInterval: 0.05
outageFrequency: null
#takes care of how long we want the visualizer to take data for. Should be greater for more traffic.
timeFactor: 1000

#visualizer parameters 
visualizerOn: 'True'
visualizeTime: 10
FPS: 3

#could add the server processing time & amount here 





