---
LEOConstellation: 'Walker Star'
NumberLEOSatellites: 360
OrbitalPlanes: 20
Inclination: 80 
phasingParameter: 5
orbitAltitudeLEO: 1000000
earthRadius: 6371
BaseStationLocations: 
  - [82.5, -62.3] 
  - [70.4, -31.1]
BaseStationViewAngle: 10
SunExclusionAngle: 40
SunLocation: [149.6e+6, 0, 0]
