---
#config file. some parameters are not compatable with others....
#some inherent restrictions exist, like: numberLEO%oprbitalPlanes

#constellation parameters
#walkerDelta or square  
LEOConstellation: 'walkerDelta'
NumberLEOSatellites: 28
OrbitalPlanes: 4
Inclination: 80 
phasingParameter: 5
orbitAltitudeLEO: 1000000

#base station and environment parameters 
earthRadius: 6371000
BaseStationLocations: 
  - [82.5, -62.3] 
  - [70.4, -31.1]
BaseStationViewAngle: 10
SunExclusionAngle: 40
SunLocation: [149.6e+6, 0, 0]

#topology and routing polocy / satellite info
#either basicSquare or IPO
initialTopology: 'IPO'
#possible values: 
#OSPF, basic, mixedSingleAgentRLRestOSPF, RL
routingPolicy: 'RL'
topologyPolicy: null
#RL training: [[100,90,100,10]]
#testing saturation: [[10, 9, 10, 1 ]]
#normal behavior: 100
#cant be 1d array 
packetProcessRate: 10 #[[10, 9, 10, 1 ]]

#simulation runtime parameters 
numPeople: 1
numPacketsPerPerson: 500
packetSendTimeFrame: 1
#PseudoUniform, SingleFar, simpleForSingleRL
#cant use single far with multiple people 
personDistribution: 'simpleForSingleRL'
#can be Even or Uniform
sendTimeDistribution: 'Uniform'

queingDelaysEnabled: True
weatherEnabled: False
#was .05 for first graphic...
environmentUpdateInterval: 10
outageFrequency: null
#takes care of how long we want the visualizer to take data for. Should be greater for more traffic.
#its a ratio of the visualize time vs the time frame length that packets are being sent over. 
timeFactor: 100

#visualizer parameters 
visualizerOn: False
visualizeTime: 10
FPS: 3

dynamicLocation: False
#this needs to be None if working with non RL method/decision style
#can either be centralized or distributed. distributed if single RL agent
RLTrainingMethod: 'distributed' 





