---

#constellation parameters
#walkerDelta or square  
LEOConstellation: 'square' #'walkerDelta'
NumberLEOSatellites: 360
OrbitalPlanes: 20
Inclination: 80 
phasingParameter: 5
orbitAltitudeLEO: 1000000

#base station and environment parameters 
earthRadius: 6371000
BaseStationLocations: 
  - [82.5, -62.3] 
  - [70.4, -31.1]
BaseStationViewAngle: 10
SunExclusionAngle: 40
SunLocation: [149.6e+6, 0, 0]

#topology and routing polocy / satellite info
#either basicSquare or IPO
initialTopology: 'basicSquare'
#possible values: 
#OSPF, basic, mixedSingleAgentRLRestOSPF
routingPolicy: 'mixedSingleAgentRLRestOSPF'
topologyPolicy: null
#RL training: [[100,70,100,30]]
#normal behavior: 100
#cant be 1d array 
packetProcessRate: [[100,90,300,10]]

#simulation runtime parameters 
numPeople: 1
numPacketsPerPerson: 500
packetSendTimeFrame: 5
#PseudoUniform, SingleFar, simpleForSingleRL
#cant use single far with multiple people 
personDistribution: 'simpleForSingleRL'
sendTimeDistribution: 'Uniform'

queingDelaysEnabled: True
weatherEnabled: False
#was .05 for first graphic...
environmentUpdateInterval: 10
outageFrequency: null
#takes care of how long we want the visualizer to take data for. Should be greater for more traffic.
#its a ratio of the visualize time vs the time frame length that packets are being sent over. 
timeFactor: 1

#visualizer parameters 
visualizerOn: False
visualizeTime: 10
FPS: 3

dynamicLocation: False
RLTrainingMethod: 'distributed'
#could add the server processing time & amount here 





